{{- if .Values.configmap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-deployment.fullname" . }}
  labels:
    app: {{ include "app-deployment.name" . }}
    helm.sh/chart: {{ include "app-deployment.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.configmap.data }}
data:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}