apiVersion: v1
kind: Service
metadata:
  name: {{ include "template-deploy.fullname" . }}
  labels:
    {{- include "template-deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}    # NodePort, ClusterIP, LoadBalancer, ExternalIP
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .externalPort }}
      targetPort: {{ .internalPort }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "template-deploy.selectorLabels" . | nindent 4 }}
