{{- if .Values.route.enabled }}
{{- range .Values.route.routes }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: "{{ include "app-deployment.fullname" $ }}-{{ .name }}"
  labels:
    app: {{ include "app-deployment.name" $ }}
    helm.sh/chart: {{ include "app-deployment.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
{{- with $.Values.route.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .spec }}
spec:
{{ toYaml . | indent 2 }}
{{- end }}
{{- end }}
{{- end }}