# Default values for generic-deployment.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nexus-registry.pttdigital.com/pttdevops-demo/app
  tag: "latest"
  pullPolicy: Always

nameOverride: app
fullnameOverride: app

configmap:
  enabled: false
  data:
  # put your configmap data here as
  # key: value
    foo: bar

env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  # Using configmap from this Chart just use key name
  # - name: FOO_FROM_CONFIGMAP_ABOVE
  #   configmap:
  #     key: foo
  # Using other configmap need configmap's name
  # - name: BAZ_FROM_OTHER
  #   configmap:
  #     name: baz-configmap
  #     key: baz

envFrom:
  # - secret:
  #     name: secret01
  # - prefix: PF_ (if you want to put prefix on every key name)
  #   configmap:
  #     name: (leave blank to use configMap from this Chart)
  # - configmap:
  #     name: configmap02

volumeMounts:
  # - name: sample-storage-volume
  #   mountPath: /usr/src/app/pv-folder

volumes:
  # - name: sample-storage-volume
  #   persistentVolumeClaim:
  #     claimName: sample-storage

containerPorts:
  - 5106

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 1
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

service:
  enabled: false
  type: ClusterIP
  annotation: {}
  ports:
    - name: app-svc
      protocol: TCP
      externalPort: 80
      internalPort: 5106

serviceHeadless:
  enabled: false

route:
  enabled: false
  routes:
    - name: route-1
      spec:
        to:
          kind: Service
          name: app
          weight: 100
        port:
          targetPort: app-svc
        wildcardPolicy: None

healthCheck:
  enabled: false
  readinessProbe:
    #httpGet:
    #  path: /ready
    #  port: 80
    initialDelaySeconds: 0
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  livenessProbe:
    #httpGet:
    #  path: /health
    #  port: 80
    initialDelaySeconds: 0
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3